name: Run QA now

on:
  workflow_dispatch:
    inputs:
      passphrase:
        description: 'Secret phrase'
        required: true
      input_zip_b64:
        description: 'Base-64 of input.zip'
        required: true

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
    # ─────────────────── 1 · Gatekeeper ───────────────────
    - name: Validate pass-phrase
      run: |
        if [ -z "${{ github.event.inputs.passphrase }}" ]; then
          echo "::error ::Pass-phrase is missing. Ensure you provide the passphrase when triggering the workflow."
          exit 1
        fi
        if [ "${{ github.event.inputs.passphrase }}" != "${{ secrets.QA_PASSPHRASE }}" ]; then
          echo "::error ::Incorrect pass-phrase. Check the QA_PASSPHRASE secret in repository settings."
          exit 1
        fi

    # ─────────────────── 2 · Checkout code ─────────────────
    - uses: actions/checkout@v4

    # ─────────────────── 3 · Ensure package-lock.json exists ──────────
    - name: Ensure package-lock.json exists
      run: |
        if [ ! -f package-lock.json ]; then
          echo "::error ::package-lock.json is missing. Please add it to the repository."
          exit 1
        fi

    # ─────────────────── 4 · Install deps ─────────────────
    - name: Install Node deps
      run: npm ci

    # ─────────────────── 5 · Recreate input.xlsx ───────────
    - name: Restore input.xlsx from Base-64 zip
      run: |
        echo "${{ github.event.inputs.input_zip_b64 }}" | base64 -d > input.zip
        unzip -o input.zip

    # ─────────────────── 6 · Run the crawler ──────────────
    - name: Run QA
      run: node qa-test.js input.xlsx

    # ─────────────────── 7 · Upload results ───────────────
    - uses: actions/upload-artifact@v4
      with:
        name: results-${{ github.run_id }}
        path: results-*.xlsx