name: Run QA now

on:
  workflow_dispatch:
    inputs:
      passphrase:
        description: 'Secret phrase'
        required: true
      input_zip_b64:
        description: 'Base-64 of input.zip'
        required: true

jobs:
  qa:
    if: ${{ github.event.inputs.passphrase == secrets.QA_PASSPHRASE }}
    runs-on: ubuntu-latest

    steps:
    - name: Fail if pass-phrase empty (defence-in-depth)
      if: ${{ github.event.inputs.passphrase == '' }}
      run: |
        echo "Pass-phrase missing" >&2
        exit 1

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Node deps
      run: npm ci

    - name: Create input.zip from Base-64
      run: |
        echo "${{ github.event.inputs.input_zip_b64 }}" | base64 -d > input.zip
        unzip -o input.zip

    - name: Run QA
      run: node qa-test.js input.xlsx

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: results-${{ github.run_id }}
        path: results-*.xlsx

  wrong-pass:
    if: ${{ github.event.inputs.passphrase != secrets.QA_PASSPHRASE }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::error ::Bad pass-phrase – QA not started"
